name: Serverless Deployment

on:
    push:
        branches:
            - serverless

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install Node
              uses: actions/setup-node@v4
              with: 
                node-version: 20

            - name: Install Dependencies
              run: npm ci

            # - name: Test Scripts - Haven't configured testing for scripts, might be nice to do sometime
            #   run: npm test
            
            - name: Build Code
              run: npm run build