name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Remove existing build directory
        run: rm -rf /var/www/jaylowry.com/resume-site/build

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Get updated code via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/jaylowry.com/resume-site
            git pull --force